import type { Metadata } from "next";
import { Geist, Geist_Mono, Funnel_Display, Poppins } from "next/font/google";
import './style.css';
import "./globals.css";
import {Toaster} from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const funnelDisplay = Funnel_Display({
  variable: "--font-funnel-display",
  subsets: ['latin'],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ['latin'],
  weight: ["100" , "200" , "300" , "400" , "500" , "600" , "700" , "800" , "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${funnelDisplay.variable} ${poppins.variable} font-poppins antialiased`}
      >
        <Toaster/>
        {children}
      </body>
    </html>
  );
}
